In [ ]:
import numpy as np
import pandas as pd
import joblib

In [ ]:
pay=pd.read_csv('payment_data.csv')
cus=pd.read_csv('customer_data.csv')

In [ ]:
primary_key_column = 'id'
merged_data = pd.merge(cus, pay, on=primary_key_column)

In [ ]:
columns_to_drop = ['report_date','update_date','prod_limit','highest_balance']
# Drop the specified feature columns
dataset_dropped = merged_data.drop(columns=columns_to_drop, axis=1)

In [ ]:
from sklearn.impute import KNNImputer
impute = KNNImputer(n_neighbors= 3)
dataset_dropped['fea_2'] = impute.fit_transform(dataset_dropped[['fea_2']])

In [ ]:
X=dataset_dropped.iloc[:,2:]
y=dataset_dropped['label']

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import accuracy_score



In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
logreg = LogisticRegression(random_state=42)
dtree = DecisionTreeClassifier(random_state=42)
rf = RandomForestClassifier(random_state=42)
gboost = GradientBoostingClassifier(random_state=42)
svm = SVC(probability=True, random_state=42)
nn = MLPClassifier(random_state=42)
knn = KNeighborsClassifier()
nb = GaussianNB()
xgboost = XGBClassifier(random_state=42)
lightgbm = LGBMClassifier(random_state=42)

In [ ]:
ensemble = VotingClassifier(estimators=[('logreg', logreg), ('dtree', dtree), ('rf', rf),('gboost', gboost),
    ('svm', svm),
    ('nn', nn),
    ('knn', knn),
    ('nb', nb),
    ('xgboost', xgboost),
    ('lightgbm', lightgbm),
    ], voting='hard')
ensemble.fit(X_train, y_train)

logreg.fit(X_train,y_train)
dtree.fit(X_train,y_train)
rf.fit(X_train,y_train)
gboost.fit(X_train,y_train)
svm.fit(X_train,y_train)
nn.fit(X_train,y_train)
knn.fit(X_train,y_train)
nb.fit(X_train,y_train)
xgboost.fit(X_train,y_train)
lightgbm.fit(X_train,y_train)


LGBMClassifier(random_state=42)

In [ ]:

ensemble_predictions = ensemble.predict(X_test)
logreg_pred=logreg.predict(X_test)
dtree_pred=dtree.predict(X_test)
rf_pred=rf.predict(X_test)
gboost_pred=gboost.predict(X_test)
svm_pred=svm.predict(X_test)
nn_pred=nn.predict(X_test)
knn_pred=knn.predict(X_test)
nb_pred=nb.predict(X_test)
xgboost_pred=xgboost.predict(X_test)
lightgbm_pred=lightgbm.predict(X_test)


accuracy = accuracy_score(y_test, ensemble_predictions)
print("Ensemble Accuracy:", accuracy)

accuracy1 = accuracy_score(y_test, logreg_pred)
print("logistic_reg Accuracy:", accuracy1)

accuracy2 = accuracy_score(y_test,dtree_pred)
print("descision Accuracy:", accuracy2)

accuracy3 = accuracy_score(y_test,rf_pred)
print("random forest:", accuracy3)

accuracy4 = accuracy_score(y_test, gboost_pred)
print("gboost Accuracy:", accuracy4)

accuracy5 = accuracy_score(y_test, svm_pred)
print("svm Accuracy:", accuracy5)

accuracy6 = accuracy_score(y_test, nn_pred)
print("nn Accuracy:", accuracy6)

accuracy7 = accuracy_score(y_test, knn_pred)
print("knn Accuracy:", accuracy7)


accuracy8 = accuracy_score(y_test, nb_pred)
print("nb Accuracy:", accuracy8)

accuracy9 = accuracy_score(y_test, xgboost_pred)
print("xgboost Accuracy:", accuracy9)

accuracy10 = accuracy_score(y_test,lightgbm_pred)
print("lightgbm Accuracy:", accuracy10)


Ensemble Accuracy: 0.8709090909090909
logistic_reg Accuracy: 0.8375757575757575
descision Accuracy: 0.9860606060606061
random forest: 0.9733333333333334
gboost Accuracy: 0.8824242424242424
svm Accuracy: 0.8387878787878787
nn Accuracy: 0.8006060606060607
knn Accuracy: 0.8684848484848485
nb Accuracy: 0.8272727272727273
xgboost Accuracy: 0.9927272727272727
lightgbm Accuracy: 0.9872727272727273


In [ ]:
import pandas as pd

# Prepare new data point
new_data_point = {
    'OVD_sum':float(input()),
    'OVD_t1': float(input()),
    'OVD_t2': float(input()),
    'OVD_t3': float(input()),
    'fea_10': float(input()),
    'fea_1': float(input()),
    'fea_11': float(input()),
    'fea_2': float(input()),
    'fea_3': float(input()),
    'fea_4': float(input()),
    'fea_5': float(input()),
    'fea_6': float(input()),
    'fea_7': float(input()),
    'fea_8': float(input()),
    'fea_9': float(input()),
    'new_balance': float(input()),
    'pay_normal': float(input()),
    'prod_code': float(input()),
}
new_data_df = pd.DataFrame([new_data_point])

new_data_df = new_data_df[X_train.columns]


# Make predictions
logreg_pred = logreg.predict(new_data_df)
dtree_pred = dtree.predict(new_data_df)
rf_pred = rf.predict(new_data_df)
gboost_pred = gboost.predict(new_data_df)
svm_pred = svm.predict(new_data_df)
nn_pred = nn.predict(new_data_df)
knn_pred = knn.predict(new_data_df)
nb_pred = nb.predict(new_data_df)
xgboost_pred = xgboost.predict(new_data_df)
lightgbm_pred = lightgbm.predict(new_data_df)
ensemble_pred = ensemble.predict(new_data_df)
detected=[]
# Print predictions
print("Individual Model Predictions:")
print("Logistic Regression:", logreg_pred)
print("Decision Tree:", dtree_pred)
print("Random Forest:", rf_pred)
print("Gradient Boosting:", gboost_pred)
print("SVM:", svm_pred)
print("Neural Network:", nn_pred)
print("KNN:", knn_pred)
print("Naive Bayes:", nb_pred)
print("XGBoost:", xgboost_pred)
print("LightGBM:", lightgbm_pred)

print("\nEnsemble Model Prediction:")
print("Ensemble:", ensemble_pred)
print('DETECTING----')

0.23
0.232
0.745
0.86356
0.098
0.
5.66
5.8765
0.344
654.5
800009.8
565.6
65.3
6564.6
6443
65.6
654.
634.6
Individual Model Predictions:
Logistic Regression: [0]
Decision Tree: [0]
Random Forest: [0]
Gradient Boosting: [1]
SVM: [0]
Neural Network: [1]
KNN: [1]
Naive Bayes: [0]
XGBoost: [0]
LightGBM: [0]

Ensemble Model Prediction:
Ensemble: [0]
DETECTING----


In [ ]:
detected=[logreg_pred,dtree_pred,rf_pred,gboost_pred,svm_pred,nn_pred,nb_pred,knn_pred,xgboost_pred,lightgbm_pred]

In [ ]:
noof1=0
noof0=0
for i in detected:
  if i==1:
    noof1+=1
  else:
    noof0+=1

In [ ]:
list(detected)

[array([0]),
 array([0]),
 array([0]),
 array([1]),
 array([0]),
 array([1]),
 array([0]),
 array([1]),
 array([0]),
 array([0])]

In [ ]:
print(noof1,noof0)

3 7


In [ ]:
if noof1<noof0:
  print('Non-Risk')
else:
  print('Risk')


Non-Risk


In [ ]:
from flask import Flask, render_template, request

app = Flask(__name__)

# Load your trained models and other necessary libraries here
# ...

@app.route('/', methods=['GET', 'POST'])
def predict():
    if request.method == 'POST':
        # Get user input from the form
        fea_1 = float(request.form['fea_1'])
        fea_2 = float(request.form['fea_2'])
        # Include other feature values

        # Create a new data point based on user input
        new_data_point = {
            'fea_1': fea_1,
            'fea_2': fea_2,
            'OVD_sum':OVD_sum,
            'OVD_t1':OVD_t1,
            'OVD_t2':OVD_t2,
            'OVD_t3':OVD_t3,
            'fea_10':fea_10,
            'fea_1': fea_1,
            'fea_11':fea_11,
            'fea_2':fea_2,
            'fea_3':fea_3,
            'fea_4':fea_4,
            'fea_5':fea_5,
            'fea_6':fea_6,
            'fea_7':fea_7,
            'fea_8':fea_8,
            'fea_9':fea_9,
            'new_balance':new_balance,
            'pay_normal':pay_normal ,
            'prod_code': prod_code,
            # Include other feature values
        }

        # Convert the data point to a DataFrame
        new_data_df = pd.DataFrame([new_data_point])
        new_data_df = new_data_df[X_train.columns]

        # Make predictions using the ensemble model
        ensemble_pred = ensemble.predict(new_data_df)

        # Determine the prediction outcome
        prediction_outcome = "Default" if ensemble_pred == 1 else "Non-default"

        return render_template('result.html', prediction_outcome=prediction_outcome)

    return render_template('index.html')

if __name__ == '__main__':
    app.run(debug=True)


 * Serving Flask app '__main__'
 * Debug mode: on


INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
INFO:werkzeug:Press CTRL+C to quit
INFO:werkzeug: * Restarting with stat
